// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQNjjS7A1tsOglkZ3SqXMkH7nz1Kr6Yc',
    appId: '1:899838297043:web:2d3d65a18ac4413b58a526',
    messagingSenderId: '899838297043',
    projectId: 'emergency-safety-sos',
    authDomain: 'emergency-safety-sos.firebaseapp.com',
    storageBucket: 'emergency-safety-sos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhWsEXTVb-yCmJIjiwYisuFC8fpmroUQ',
    appId: '1:899838297043:android:da9c453b6a50210058a526',
    messagingSenderId: '899838297043',
    projectId: 'emergency-safety-sos',
    storageBucket: 'emergency-safety-sos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1I25ioIsUiOBItLsK4fgVKDm777w9Sk',
    appId: '1:899838297043:ios:0565de98baacd8a558a526',
    messagingSenderId: '899838297043',
    projectId: 'emergency-safety-sos',
    storageBucket: 'emergency-safety-sos.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1I25ioIsUiOBItLsK4fgVKDm777w9Sk',
    appId: '1:899838297043:ios:0565de98baacd8a558a526',
    messagingSenderId: '899838297043',
    projectId: 'emergency-safety-sos',
    storageBucket: 'emergency-safety-sos.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUQNjjS7A1tsOglkZ3SqXMkH7nz1Kr6Yc',
    appId: '1:899838297043:web:56ab276580104c6658a526',
    messagingSenderId: '899838297043',
    projectId: 'emergency-safety-sos',
    authDomain: 'emergency-safety-sos.firebaseapp.com',
    storageBucket: 'emergency-safety-sos.firebasestorage.app',
  );
}
